name: Code Deployment
on: 
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3

      - name: Linting check
        run: npm run lint
  Test:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      
      - name: Testing Code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v3
      - name: Deployment
        run: npm run build